name: Deploy to Production
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build:prod
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: prod
          channelId: live
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_APP_547FA }}'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Update prod branch
        run: |
          git fetch
          git push origin HEAD:prod
      - name: Create Release Tag
        run: |
          RELEASE_TAG="PROD-$(date +'%Y%m%d')#${GITHUB_RUN_NUMBER}"
          git tag $RELEASE_TAG
          git push -f origin $RELEASE_TAG
